### ISSUE TITLE
TypeError: lcSDK.AgentAPI is not a constructor

### ISSUE THREAD

**Issue by vinayjayaram** [livechat/lc-sdk-js#3]
I am trying to clone SDK and start integrating to my nodejs project.
My index.js looks like this 
```
const lcSDK = require("./lc-sdk-js");


const agentAPI = new lcSDK.AgentAPI("XXXXXXXX", () => ({
    licenseID: XXXX,
    accessToken: "fra:Bub7epvmQqqnwTKFrr7NGQ",
    region: "fra"
  }));
```
when i run my code i get an error 
 const agentAPI = new lcSDK.AgentAPI("XXXXXXX", () => ({
                     ^

TypeError: lcSDK.AgentAPI is not a constructor
    at agent (C:\Users\M1056438\Documents\Unilever\WhatsAppUsecase\testLiveChatSDK\indes.js:4:22)
    at Object.<anonymous> (C:\Users\M1056438\Documents\Unilever\WhatsAppUsecase\testLiveChatSDK\indes.js:11:1)
    at Module._compile (internal/modules/cjs/loader.js:956:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
    at Module.load (internal/modules/cjs/loader.js:812:32)
    at Function.Module._load (internal/modules/cjs/loader.js:724:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1025:10)
    at internal/main/run_main_module.js:17:11

**Comment by wfabjanczuk** [comment]
Hello, I know this is too late and I am sorry for that. For examples on how to use SDK see the `/examples` folder (we recommend TypeScript). 

Creating Agent API instance in the current stable v3.5 is shown here:

- https://github.com/livechat/lc-sdk-js/blob/v3.5/examples/rtm-messages/index.ts
- https://github.com/livechat/lc-sdk-js/blob/v3.5/examples/bot-integration/src/livechat/livechat.service.ts
